apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bindplane
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: bindplane-agent
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: kubernetes/apps/bindplane
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: {{ .Values.spec.automated.prune }}
